In [73]:
# main implementation file
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [74]:
class Perceptron:
    def __init__(self, learning_rate, epochs):
        """Initialize the perceptron with random weights"""
        self.weights = np.random.randn(3) * 1e-4
        self.learning_rate = learning_rate
        self.epochs = epochs
        print(f"Initial weights: {self.weights}")
    
    def activation_function(self, inputs, weights):
        """Apply step function: output 1 if sum > 0, else 0"""
        weighted_sum = np.dot(inputs, weights)
        return np.where(weighted_sum > 0, 1, 0)
    
    def fit(self, X, y):
        """Train the perceptron model"""
        self.X = X
        self.y = y
        
        # Add bias term to features
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"\nX with bias:\n{X_with_bias}\n")
        
        # Training loop
        for epoch in range(self.epochs):
            epoch_results = []
            
            for sample_idx, (features, target) in enumerate(zip(X_with_bias, self.y)):
                # Make prediction
                prediction = self.activation_function(features, self.weights)
                
                # Calculate error
                error = target - prediction
                
                # Update weights
                self.weights += self.learning_rate * error * features
                
                # Format weights for display (round to 4 decimals)
                w1, w2, w3 = np.round(self.weights, 4)
                weights_str = f"[{w1}, {w2}, {w3}]"
                
                # Store training info for this epoch
                epoch_results.append({
                    'Sample': sample_idx + 1,
                    'Target': int(target),
                    'Prediction': int(prediction),
                    'Error': int(error),
                    'W1': w1,
                    'W2': w2,
                    'Bias': w3
                })
            
            # Display table for this epoch
            epoch_table = pd.DataFrame(epoch_results)
            print(f"EPOCH {epoch + 1}")
            print("-" * 52)
            print(epoch_table.to_string(index=False))
            print()
        
        print("="*52)
        print("Training complete!")
    
    def predict(self, X):
        """Make predictions on new data"""
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        return self.activation_function(X_with_bias, self.weights)

In [75]:
model = Perceptron(learning_rate=0.1, epochs=10)
data = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,0,0,1]
}
AND = pd.DataFrame(data)
X = AND.drop("y", axis=1)
y = AND["y"]
model.fit(X, y)
predictions = model.predict(X)
print(f"\nFinal predictions: {predictions}")

Initial weights: [-1.11188012e-04  3.18902185e-05  2.79041292e-05]

X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]

EPOCH 1
----------------------------------------------------
 Sample  Target  Prediction  Error      W1   W2  Bias
      1       0           0      0 -0.0001  0.0   0.0
      2       0           1     -1 -0.0001 -0.1   0.1
      3       0           0      0 -0.0001 -0.1   0.1
      4       1           0      1  0.0999  0.0   0.0

EPOCH 2
----------------------------------------------------
 Sample  Target  Prediction  Error     W1   W2  Bias
      1       0           0      0 0.0999  0.0   0.0
      2       0           1     -1 0.0999 -0.1   0.1
      3       0           0      0 0.0999 -0.1   0.1
      4       1           0      1 0.1999  0.0   0.0

EPOCH 3
----------------------------------------------------
 Sample  Target  Prediction  Error     W1   W2  Bias
      1       0           0      0 0.1999  0.0   0.0
      2       0           1    

In [76]:
import numpy as np
w = np.array([2,2])
x = np.array([3,4])
y = np.dot(w, x)
print(y)  # Output: 14
# its just weighted sum of inputs

14


In [77]:
# Normal Distribution
random = np.random.seed(42)

In [78]:
random_normal = np.random.rand(3)
print(random_normal)

[0.37454012 0.95071431 0.73199394]


In [79]:
# concatenation
import pandas as pd
data = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,0,0,1]
}

AND = pd.DataFrame(data)
print(AND)

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1


In [80]:
X = AND.drop("y", axis=1)
y = AND["y"]
y.to_frame()
print(X)
print(y)

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1
0    0
1    0
2    0
3    1
Name: y, dtype: int64


In [81]:
bias = np.c_[X, -np.ones((len(X),1))]
print(bias)

[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
