In [ ]:
import numpy as np
w = np.array([2,2])
x = np.array([3,4])
y = np.dot(w, x)
print(y)  # Output: 14
# its just weighted sum of inputs

14


In [2]:
# Normal Distribution
random = np.random.seed(42)

In [4]:
random_normal = np.random.rand(3)
print(random_normal)

[0.15601864 0.15599452 0.05808361]


In [5]:
# concatenation
import pandas as pd
data = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,0,0,1]
}

AND = pd.DataFrame(data)
print(AND)

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1


In [7]:
X = AND.drop("y", axis=1)
y = AND["y"]
y.to_frame()
print(X)
print(y)

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1
0    0
1    0
2    0
3    1
Name: y, dtype: int64


In [13]:
bias = np.c_[X, -np.ones((len(X),1))]
print(bias)

[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
